# Use an official JDK as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the local Maven project to the container
COPY ./target/spring-app.jar /app/spring-app.jar

# Expose the port the app will run on
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "spring-app.jar"]
